services:
  postgres:
    image: postgres:16-alpine
    container_name: pass_manager_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pass_manager
      POSTGRES_PASSWORD: pass_manager
      POSTGRES_DB: pass_manager
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pass_manager -d pass_manager"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pass_manager_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pass_manager_api
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-pass_manager}
      DB_PASSWORD: ${DB_PASSWORD:-pass_manager}
      DB_NAME: ${DB_NAME:-pass_manager}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-true}
      JWT_SECRET: ${JWT_SECRET:-high_win_n240h}
      JWT_FIRST_LOGIN_SECRET: ${JWT_FIRST_LOGIN_SECRET:-first_login_high_win_n240h}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
